version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 5s
      timeout: 5s
      retries: 5

  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
    environment:
      - DB=postgres12
      - POSTGRES_SEEDS=postgres
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy

  temporal-ui:
    image: temporalio/ui:latest
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8080
    depends_on:
      - temporal

  shipment-app:
    build: .
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - temporal
      - roulette

  roulette:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install --no-cache-dir -r requirements.txt && python roulette.py"
    volumes:
      - ./downstream:/app   # mount downstream service code
      - appdata:/data
    environment:
      - PORT=8000
      - FLASK_DEBUG=1
      - FAILURE_RATE=0.4
      - RETRY_AFTER_MIN=1
      - RETRY_AFTER_MAX=3
      - DATABASE_URL=sqlite:////data/app.db
      - ALLOW_RESET_WITHOUT_LOCK=1
      - ENFORCE_ADJACENT=1
    ports:
      - "8000:8000"

volumes:
  appdata:
